### ISSUE TITLE
Size issue - Cropped buttons

### ISSUE THREAD

**Issue by hoppfrosch** [TheArkive/ahk-pi#2]
Running your provided compiled version (v1.5) in the lower left corner are cropped buttons ... either the dialog box is to big or to small ...

![AHK_Portable_Installer_U64_he8rlW0fNM](https://user-images.githubusercontent.com/419075/76849547-e27b8780-6845-11ea-9dee-5a2c18a0d89a.png)

**Comment by TheArkive** [comment]
Thanks for that.  Might be a scaling issue.  I'll look into it.

When you click settings, it's supposed to expand.

**Comment by TheArkive** [comment]
Do you use scaling?  Maybe 125%?

**Comment by hoppfrosch** [comment]
I use 2 monitors - 1 with 125%, 1 with 100% ... the effect occurs on both monitors. (maybe the 125% on one monitor influences the display on both monitors)

**Comment by TheArkive** [comment]
is it fixed now?  or still a problem?  I tried scaling at 125% and it's working on my pc.

**Comment by hoppfrosch** [comment]
Yes it's fixed - thx
Just wanted to close this bug ... :-)
