### ISSUE TITLE
Folder name format

### ISSUE THREAD

**Issue by hoppfrosch** [TheArkive/ahk-pi#3]
In your current Readme.md (Commit-Id: [9ef1a85](https://github.com/TheArkive/ahk-pi/commit/9ef1a857f8c7fda56fb5257798c93a8c581fc489)) you wrote (chapter "Basic Setup"):

> Folder Name format:
    name       version
   a.) AutoHotkey vX.XX.XXX
   b.) AutoHotkey_H vX.XX.XXX
   c.) AutoHtokey vX.X-zXXX-ffffff

1.) I assume the first line a.) should represent the AutoHotkey v1-Versioning scheme. Your proposed/documented naming scheme is incomplete as the current V1-Versioning scheme consists of 4 parts: 1.1.32.00 .... you missed the last part, which is used to introduce subversions.

2.) The second line b.) should be used for AutoHotkey_H. This is also implemented/documented incompletely as AutoHotkey_H provides v1 and a v2 support, which are corresponding the standard AutoHotkey versions. So there should be support for both versioning scheme variants:
-  AutoHotkey_H vX.XX.XXX.XX
- AutoHotkey_H vX.X-zXXX-ffffff
(maybe fffff should be omitted, as it represents the commit-Id of the standard AutoHotkey V2 version - and not of AutoHotkey_H V2...)

3.) The third line c.) has an typo (Auto**Hto**key ....)

Sorry for nitpicking, but esp. the basic documentation should be as precise as possible to allow noobs an easy start.

**Comment by TheArkive** [comment]
Actually, the folder name format is technically this:
[name_no_spaces] [version_no_spaces]

 ... lol ... all those X's and f's were just trying to illustrate examples.

You could write:
`AHK puppydog`
and the version would be `puppydog`

I'll change the docs :-P

**Comment by hoppfrosch** [comment]
You might document the "puppydog" example as well to document the version string being a "free" string.
Just was a little confused in the beginning, cause your example referred directly to versioning scheme of AutoHotkey - but not precisely.

**Comment by hoppfrosch** [comment]
Opps ... premature closed by accident :-)

**Comment by TheArkive** [comment]
I've changed the docs.  Looking more clear?

**Comment by hoppfrosch** [comment]
Looks great now ... :-)
